version: '3.8'

services:
  db:
    image: postgres:15
    container_name: budgetwise-db
    env_file:
      - environments/postgres.example.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - budgetwise-net

  main_app:
    build: ./microservices/main_app
    container_name: budgetwise-app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ./microservices/main_app:/app
    networks:
      - budgetwise-net

volumes:
  postgres_data:

networks:
  budgetwise-net:
